version: "3"
services:
  gateway-service:
    build: 
      context: ./gateway-service
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  backend:
