version: "3"
services:
  front-end:
    stdin_open: true
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "80:80"
    networks:
      - frontend
  eureka-service:
    build:
      context: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - backend
  gateway-service:
    build: 
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081"
    networks:
      - backend
    depends_on:
      - database
  status-service:
    build:
      context: ./status-service
    container_name: status-service
    ports:
      - "8082"
    networks:
      - backend
    depends_on:
      - database
  database:
    image: postgres
    container_name: database
    ports:
      - "5432"
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  frontend:
  backend: